# This is a basic workflow to help you get started with Actions

name: dogbot-times-holiday-booking

# Controls when the action will run. 
on:
  schedule:
    - cron: "58 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git clone https://github.com/fffuturework/dogbot
          cd dogbot
          npm i
          cd ..
          rm -rf dogbot
